config/routes.rb
ZeroPaperTeste::Application.routes.draw do
    
  resources :galinhas

  resources :ovos

  root to: "galinhas#index"

  

end

app/models/galinha.rb
class Galinha < ActiveRecord::Base
  
  has_many :ovos, dependent: :destroy
  
end

app/models/ovo.rb
class Ovo < ActiveRecord::Base

	belongs_to :galinha

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galinhas_controller.rb
class GalinhasController < ApplicationController
  before_action :set_galinha, only: [:show, :edit, :update, :destroy]

  # GET /galinhas
  # GET /galinhas.json
  def index
    @galinhas = Galinha.all
  end

  # GET /galinhas/1
  # GET /galinhas/1.json
  def show
    @ovos = Ovo.where(galinha_id: @galinha.galinha_id)
  end

  # GET /galinhas/new
  def new
    @galinha = Galinha.new
  end

  # GET /galinhas/1/edit
  def edit
    @galinha = Galinha.find(params[:id])
  end

  # POST /galinhas
  # POST /galinhas.json
  def create
    @galinha = Galinha.new(galinha_params)

    #Parte destinada a fazer o auto_increment do id    
    count_objs = Galinha.count()
    unless count_objs 
      endcount_objs = 0 
    end 
    
    @galinha.galinha_id = count_objs+1
    #Fim da automatização de incrementação do id

    respond_to do |format|
      if @galinha.save
        format.html { redirect_to @galinha, notice: 'Galinha was successfully created.' }
        format.json { render action: 'show', status: :created, location: @galinha }
      else
        format.html { render action: 'new' }
        format.json { render json: @galinha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galinhas/1
  # PATCH/PUT /galinhas/1.json
  def update
    respond_to do |format|
      if @galinha.update(galinha_params)
        format.html { redirect_to @galinha, notice: 'Galinha was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @galinha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galinhas/1
  # DELETE /galinhas/1.json
  def destroy
    @galinha.destroy
    respond_to do |format|
      format.html { redirect_to galinhas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galinha
      @galinha = Galinha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galinha_params
      params.require(:galinha).permit(:galinha_id, :nome, :raca)
    end
end

app/controllers/ovos_controller.rb
class OvosController < ApplicationController
  before_action :set_ovo, only: [:show, :edit, :update, :destroy]

  # GET /ovos
  # GET /ovos.json
  def index
    @ovos = Ovo.all
  end

  # GET /ovos/1
  # GET /ovos/1.json
  def show
  end

  # GET /ovos/new
  def new
    @ovo = Ovo.new
  end

  # GET /ovos/1/edit
  def edit
  end

  # POST /ovos
  # POST /ovos.json
  def create
    @ovo = Ovo.new(ovo_params)

    #Parte destinada a fazer o auto_increment do id    
    count_objs = Ovo.count()
    unless count_objs 
      endcount_objs = 0 
    end 
    
    @ovo.ovo_id = count_objs+1
    #Fim da automatização de incrementação do id

    respond_to do |format|
      if @ovo.save
        format.html { redirect_to @ovo, notice: 'Ovo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ovo }
      else
        format.html { render action: 'new' }
        format.json { render json: @ovo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ovos/1
  # PATCH/PUT /ovos/1.json
  def update
    respond_to do |format|
      if @ovo.update(ovo_params)
        format.html { redirect_to @ovo, notice: 'Ovo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ovo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ovos/1
  # DELETE /ovos/1.json
  def destroy
    @ovo.destroy
    respond_to do |format|
      format.html { redirect_to ovos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ovo
      @ovo = Ovo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ovo_params
      params.require(:ovo).permit(:ovo_id, :galinha_id, :cor_branco)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galinhas_helper.rb
module GalinhasHelper
end

app/helpers/ovos_helper.rb
module OvosHelper
end

app/views/galinhas/_form.html.erb
<%= form_for(@galinha) do |f| %>
  <% if @galinha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@galinha.errors.count, "error") %> prohibited this galinha from being saved:</h2>

      <ul>
      <% @galinha.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :galinha_id %><br>
    <%= f.number_field :galinha_id %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :raca %><br>
    <%= f.text_field :raca %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galinhas/edit.html.erb
<h1>Editing galinha</h1>

<%= render 'form' %>

<%= link_to 'Show', @galinha %> |
<%= link_to 'Back', galinhas_path %>

app/views/galinhas/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    
    <!-- Container que se sobrepõe a tela da fazenda -->
    <div id="contentair_content-font_farm">
      <div id="container">
        <div class="row">
          <h2 id="title_galinha" class="span5">Galinhas</h2>
          <h2 id="title_ovos" class="span6">Ovos</h2>
        </div>
        <div class="row">
          <!-- Lista de galinhas e as operações com as mesmas -->
          <table id="lista_galinhas" border="1" class="table table-hover span5">
                    <thead>
                      <th class="lista_abriga_nome_coluna">ID</th>
                      <th class="lista_abriga_nome_coluna">Nome</th>
                      <th class="lista_abriga_nome_coluna">Raça</th>
                      <th class="lista_abriga_nome_coluna">Ações</th>
                  </thead>
            
            <tbody>

              <!-- Primeira linha do corpo -->
              <tr id="exemplo_galinha" class="hidden">
                <!-- ID -->
                <td id="galinha_id_exemplo"><span>1</span></td>
                <!-- Nome -->
                <td id="galinha_nome_exemplo"><span>Jurema</span></td>
                <!-- Raça -->
                <td id="galinha_raca_exemplo"><span>Caipira</span></td>
                
                <!-- Ações -->
                <td>
                  <button title="Editar Galinha" class="tooltiper btn btn-mini btn-info"><i class="icon-edit icon-white"></i></button>
                  <button title="Visualizar Galinha" class="btn btn-mini btn-info"><i class="icon-eye-open icon-white"></i></button>
                  <button title="Excluir Galinha" class="btn btn-mini btn-danger"><i class="icon-remove icon-white"></i></button>
                </td>
              </tr>
              <!-- fim 1ª linha -->

            </tbody>
          </table>
          
          <!-- Ações de gráficos e relatórios -->
          <div id="acoes_extras" class="span2">
            <!-- Linha dos botões de cadastro -->
            <div id="acoes_cadastro" class="">

              <a id="btn_new_ovo" href="#new_ovo_modal" data-toggle="modal" title="Novo Ovo" class="btn btn-success"><i class="icon-plus icon-white"></i></a>

              <a id="btn_new_galinha" href="#new_galinha_modal" data-toggle="modal" title="Nova Galinha" class="btn btn-info"><i class="icon-plus icon-white"></i></a>
              
            </div>

          </div>

          <!-- Lista dos ovos e as operações com os mesmos -->
          <table id="lista_ovos" border="1" class="table table-hover span5">
                    <thead>
                      <th class="lista_abriga_nome_coluna">ID</th>
                      <th class="lista_abriga_nome_coluna">Mãe Nome (ID)</th>
                      <th class="lista_abriga_nome_coluna">Cor Branco</th>
                      <th class="lista_abriga_nome_coluna">Ações</th>
                  </thead>

            <tbody>

              <!-- Primeira linha do corpo -->
              <tr id="exemplo_ovo" class="hidden">
                <!-- ID -->
                <td id="ovo_id_exemplo"><span>1</span></td>
                <!-- MãeNome (ID) -->
                <td id="ovo_galinha_id_exemplo"><span class="texto_galinha">Jurema</span> (1)</td>
                <!-- Cor Branco -->
                <td id="ovo_icon-cor_exemplo"><span><i class="icon-ok"></i></span></td>
                
                <!-- Ações -->
                <td>
                  <button title="Editar Ovo" class="btn btn-mini btn-success"><i class="icon-edit icon-white"></i></button>
                  <button title="Visualizar Ovo" class="btn btn-mini btn-success"><i class="icon-eye-open icon-white"></i></button>
                  <button title="Excluir Ovo" class="btn btn-mini btn-danger"><i class="icon-remove icon-white"></i></button>
                </td>
              </tr>
              <!-- fim 1ª linha -->

            </tbody>

          </table>
        </div>
      </div>
    </div>
    <!-- fim da parte que se sobrepõe -->
  
    <!-- Parte do frame que contemlpa a fazenda -->
    <div id="block-top-a">
      <div id="catavento"></div>
      <div id="dirigivel"></div>
      
      <div class="top-a-shadow"></div> 
    </div>
    <!-- Fim da fazenda -->
    
    <!-- Modal Gráficos de produtividade Galinhas -->
    <div id="grafico" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Gráfico de desempenho das Galinhas</h3>
      </div>
      <div id="grafico_load" class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button class="btn btn-danger cancelar_modal" data-dismiss="modal" aria-hidden="true">Cancelar</button>
      </div>
    </div>

    <!-- Modal OVO -->
    <div id="new_ovo_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Formulário de Ovos</h3>
      </div>
      <div class="modal-body">
        <form accept-charset="UTF-8" action="localhost:3000/ovos" class="new_ovo form-horizontal" id="new_ovo" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="nDsgFZS0EDdv4/ms+eCMSyV32h3cjosy2v/HobDEf30=" /></div>
          <div class="field control-group">
            <label class="control-label" for="ovo_galinha_id">Galinha mãe</label><br>
            <div class="controls">
              <input id="ovo_galinha_id" name="ovo[galinha_id]" type="number" placeholder="ID da Galinha mãe"/>
              <span class="help-inline">O ID da Galinha mãe inválido</span>
            </div>
          </div>
          <div class="field control-group">
            <label class="control-label" for="ovo_cor_branco">Cor branco</label><br>
            <div class="controls">
              <input name="ovo[cor_branco]" type="hidden" value="0" /><input id="ovo_cor_branco" name="ovo[cor_branco]" type="checkbox" value="1" />
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-danger cancelar_modal" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <input id="submit_ovo" class="btn btn-success" name="commit" type="submit" value="Cadastrar" />
      </div>
    </div>
    
    <!-- Modal GALINHA -->
    <div id="new_galinha_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Formulário de Galinhas</h3>
      </div>
      <div class="modal-body">
        <form accept-charset="UTF-8" action="localhost:3000/galinhas" class="new_galinha form-horizontal" id="new_galinha" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="nDsgFZS0EDdv4/ms+eCMSyV32h3cjosy2v/HobDEf30=" /></div>
          <input id="galinha_galinha_id" name="galinha[galinha_id]" class="hidden" type="number" value="5" />
          <div class="field control-group">
            <label class="control-label" for="galinha_nome">Nome</label><br>
            <div class="controls">
              <input id="galinha_nome" name="galinha[nome]" type="text" placeholder="Nome da galinha" />
              <span class="help-inline">Nome da Galinha inválido</span>
            </div>
          </div>
          <div class="field control-group">
            <label class="control-label" for="galinha_raca">Raça</label><br>
            <div class="controls">
              <input id="galinha_raca" name="galinha[raca]" type="text" placeholder="Raça da galinha" />
              <span class="help-inline">Raça da Galinha inválida</span>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-danger cancelar_modal" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <input id="submit_galinha" class="btn btn-info" name="commit" type="submit" value="Cadastrar" />
      </div>
    </div>
    
  <script src="http://code.jquery.com/jquery-1.9.0.js"></script>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  </body>
</html>

app/views/galinhas/new.html.erb
<h1>New galinha</h1>

<%= render 'form' %>

<%= link_to 'Back', galinhas_path %>

app/views/galinhas/show.html.erb
  @#$<%= @galinha.nome %>,<%= @ovos.count %>$#@

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZeroPaperTeste</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</html>

app/views/ovos/_form.html.erb
<%= form_for(@ovo) do |f| %>
  <% if @ovo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ovo.errors.count, "error") %> prohibited this ovo from being saved:</h2>

      <ul>
      <% @ovo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ovo_id %><br>
    <%= f.number_field :ovo_id %>
  </div>
  <div class="field">
    <%= f.label :galinha_id %><br>
    <%= f.number_field :galinha_id %>
  </div>
  <div class="field">
    <%= f.label :cor_branco %><br>
    <%= f.check_box :cor_branco %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ovos/edit.html.erb
<h1>Editing ovo</h1>

<%= render 'form' %>

<%= link_to 'Show', @ovo %> |
<%= link_to 'Back', ovos_path %>

app/views/ovos/index.html.erb
<h1>Listing ovos</h1>

<table>
  <thead>
    <tr>
      <th>Ovo</th>
      <th>Galinha</th>
      <th>Cor branco</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ovos.each do |ovo| %>
      <tr>
        <td><%= ovo.ovo_id %></td>
        <td><%= ovo.galinha_id %></td>
        <td><%= ovo.cor_branco %></td>
        <td><%= link_to 'Show', ovo %></td>
        <td><%= link_to 'Edit', edit_ovo_path(ovo) %></td>
        <td><%= link_to 'Destroy', ovo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ovo', new_ovo_path %>

app/views/ovos/new.html.erb
<h1>New ovo</h1>

<%= render 'form' %>

<%= link_to 'Back', ovos_path %>

app/views/ovos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ovo:</strong>
  <%= @ovo.ovo_id %>
</p>

<p>
  <strong>Galinha:</strong>
  <%= @ovo.galinha_id %>
</p>

<p>
  <strong>Cor branco:</strong>
  <%= @ovo.cor_branco %>
</p>

<%= link_to 'Edit', edit_ovo_path(@ovo) %> |
<%= link_to 'Back', ovos_path %>